= Privacy Policy
:layout: ../../layouts/Legal.astro

== Who we are

We are the team behind the metropoliplan.org software.

The website address https://www.metropoliplan.org is a static website that explains our software in more detail.

== Data Collection by GitHub Pages

This website is hosted on GitHub Pages. GitHub Pages automatically collects standard server log data when you access this website, including:

* IP addresses
* Referrer information
* Request timestamps
* HTTP status codes
* Browser and operating system details
* Data transfer amounts

== Data Processor

*GitHub Inc.*
88 Colin P Kelly Jr St
San Francisco, CA 94107
USA

GitHub acts as the data recipient. For more information, see the link:https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement[GitHub Privacy Statement].

== Legal Basis

GitHub justifies data processing under Article 6(1)(f) of the GDPR based on legitimate interest in maintaining website stability and security. As the website operator, you have no direct access to this data and we do not engage in tracking.

== International Data Transfers

GitHub implements safeguards for international data transfers based on EU Standard Contractual Clauses (SCCs) for processing data from EU residents globally.

== Contact Information

If you have questions about this privacy policy, please contact us at: team@metropoliplan.org

== Note

This privacy policy was created with the support of link:https://opr.vc[opr.vc].
