= Privacy Policy
:layout: ../../layouts/Legal.astro

== Who we are

We are the team behind the metropoliplan.org software.

The website https://www.metropoliplan.org is a static website that explains our software in more detail.

For purely static website hosting, according to the Bavarian Data Protection Authority, this does not constitute contract data processing.

== Data Collection by GitHub Pages

This website is hosted on GitHub Pages.
The operator is GitHub Inc. 88 Colin P Kelly Jr St San Francisco, CA 94107 USA

GitHub is the recipient of your personal data.
This corresponds to our legitimate interest under Article 6(1)(f) of the GDPR, namely not having to maintain our own server infrastructure.
Server location is USA.
For more information, see the link:https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement[GitHub Privacy Statement].

GitHub Pages automatically collects standard server log data when you access this website, including:

* IP addresses
* Referrer information
* Request timestamps
* HTTP status codes
* Browser and operating system details
* Data transfer amounts

GitHub justifies data processing under Article 6(1)(f) of the GDPR based on legitimate interest in maintaining website stability and security. No tracking occurs and we have no direct access to this data.

== International Data Transfers

GitHub implements safeguards for international data transfers based on EU Standard Contractual Clauses (SCCs) for processing data from EU residents globally.

== Contact Information

If you have questions about this privacy policy, please contact us at: team@metropoliplan.org
