= Datenschutzerklärung
:layout: ../../layouts/Legal.astro

== Wer wir sind

Wir sind das Team hinter der Software metropoliplan.org.

Die Website-Adresse https://www.metropoliplan.org, ist eine statische Website die unsere Software näher erklärt.

== Datenerfassung durch GitHub Pages

Diese Website wird auf GitHub Pages gehostet. GitHub Pages erfasst automatisch Standard-Server-Protokolldaten, wenn Sie auf diese Website zugreifen, darunter:

* IP-Adressen
* Referrer-Informationen
* Anfrage-Zeitstempel
* HTTP-Status-Codes
* Browser- und Betriebssystem-Details
* Datenübertragungsmengen

== Datenverarbeiter

*GitHub Inc.*
88 Colin P Kelly Jr St
San Francisco, CA 94107
USA

GitHub fungiert als Datenempfänger. Weitere Informationen finden Sie in der link:https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement[GitHub Datenschutzerklärung].

== Rechtsgrundlage

GitHub begründet die Datenverarbeitung unter Artikel 6(1)(f) der DSGVO mit dem Interesse an der Aufrechterhaltung der Website-Stabilität und -Sicherheit. Als Website-Betreiber haben Sie keinen direkten Zugriff auf diese Daten und betreiben keine Verfolgung (Tracking).

== Internationale Datentransfers

GitHub implementiert Schutzmaßnahmen für internationale Datentransfers basierend auf EU-Standardvertragsklauseln (SCCs) für die Verarbeitung der Daten von EU-Bewohnern auf globaler Ebene.

== Kontaktinformationen

Bei Fragen zur Datenschutzerklärung kontaktieren Sie uns unter: team@metropoliplan.org

== Hinweis

Diese Datenschutzerklärung wurde mit Unterstützung von link:https://opr.vc[opr.vc] erstellt.
